### ISSUE TITLE
Allow user to add song to queue while "added to queue" pop over is shown  

### ISSUE THREAD

**Issue by nicolekalexander** [callbacc/Artistify#100]
-currently, you have to wait for the pop over to go away before you can continue adding songs to queue

**Comment by callbacc** [comment]
That's there to mainly stop spam. I don't think we'll remove that cooldown.

**Comment by IanWalston** [comment]
it's actually just the default popover behavior. 

We could limit the button at 0.2s or something but that would be too short for displaying the popover, so we do need to find away to allow the user to add songs faster while still displaying the popover.

**Comment by IanWalston** [comment]
fixed. Thanks @nicolekalexander !
