### ISSUE TITLE
Search Results: Table View

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#108]
make a table view for the search results 
allow user to switch between this view and the current grid view
make grid view the default

**Comment by Jasper-Mui** [comment]
I would be interested in trying this. 
What are you looking for per search result for each row? 
Are you looking for just the name, thumbnail, play functionality, and queue functionality?
Do you want to use material-ui's table component for this?

**Comment by callbacc** [comment]
Just the name, thumbnail, play and queue functionality. And yes, we prefer using material-ui’s table component.

**Comment by IanWalston** [comment]
For the material ui component, you could use table, grid, or data-grid. 

You could also include author and view count as columns. 

THANKS!
