### ISSUE TITLE
user counter

### ISSUE THREAD

**Issue by callbacc** [callbacc/Artistify#39]
so add a counter in the appbar that will display the people that are using the app

**Comment by IanWalston** [comment]
possible solution: 

- use `express-sessions`

- look at this example api endpoint that will return all sessions:
```
router.get('/sessions', (req, res) => {
  req.sessionStore.sessionModel.findAll()
    .then(sessions => sessions.map(sess => JSON.parse(sess.dataValues.data)))
    .then((sessions) => {
      res.send(sessions)
    })
})
```
- alter this endpoint to return only the number of active sessions, not the entire session data.
