### ISSUE TITLE
DB queries are susceptible to SQL injection

### ISSUE THREAD

**Issue by gregoriB** [callbacc/Artistify#4]
The mysql NPM package has this covered:
https://www.npmjs.com/package/mysql#escaping-query-values

**Comment by callbacc** [comment]
We'll take a look at that. Thanks for the issue!

**Comment by callbacc** [comment]
Me and Dangle are starting to work on the issues. They'll be fixed in some hours.

**Comment by gregoriB** [comment]
If you reference the issue in the commit message, github should automatically link the commit and issue, ie:
> addressed issue #4 escape variables in queries

**Comment by callbacc** [comment]
They're fixed now.
You can pull the repo again.
