### ISSUE TITLE
new video card design

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#41]
![image](https://user-images.githubusercontent.com/42522279/95246332-4f566f00-07e2-11eb-913d-a5d0c50817f2.png)

**Comment by IanWalston** [comment]
https://material-ui.com/components/cards/

**Comment by blambert1080** [comment]
Hello, I'd love to work on this

**Comment by callbacc** [comment]
Go ahead!

**Comment by Jardimjose** [comment]
blambert ,if you would like to communicate with the other devs let us know
