### ISSUE TITLE
video card details button

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#51]
add button to video search result card that display extra information about the video

the information should include the artist, full title, duration, anything other relative data we're getting in the response 

details could pop up in a little modal or popover or something like that 

this will allow users to learn more about a video search result before playing it or adding it to the queue

**Comment by Austinfrbs** [comment]
We are going to need the meta data which can be pulled using the api key so we might need to build a separate module to handle the meta data. Ive found this npm package which achieves that but it would need to run in parallel with our current scraper. https://www.npmjs.com/package/youtube-info
