### ISSUE TITLE
Error: Cannot find module 'yt-search'

### ISSUE THREAD

**Issue by Shrirang97** [callbacc/Artistify#52]
Error: Cannot find module 'yt-search'

![image](https://user-images.githubusercontent.com/28738668/95375943-f976e980-08fd-11eb-8d65-24550d2c591f.png)

**Comment by callbacc** [comment]
"npm i yt-search"

**Comment by Shrirang97** [comment]
Yes. that module is not there. but
master code should not contain such error
Please update master branch.

**Comment by IanWalston** [comment]
this issue has been fixed
