### ISSUE TITLE
In Video Cards, Replace "Play" and "Add to Queue" buttons with icon buttons

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#6]
The "Play" button could be a triangle play icon 
The "Add to Queue" button could be a plus sign

use material-ui icons

**Comment by nxtcoder17** [comment]
I would like to work on this issue, please assign it to me

**Comment by nxtcoder17** [comment]
I made this [pull request](https://github.com/callbacc/Artistify/pull/14). Do Look into it.
