### ISSUE TITLE
Stop queue button from adding the same song multiple times 

### ISSUE THREAD

**Issue by Jardimjose** [callbacc/Artistify#78]
Currently, when you click the add to the queue to button on the song card it lets you add the same song as much you want, it should say "already added" if you've added it once.

**Comment by IanWalston** [comment]
lets dsiaply a warning to the user that they're adding something that's already in the queue, and the user can confirm or deny

**Comment by IanWalston** [comment]
it now shows "added to list" for each time it adds, and prevents spamming the button.
