### ISSUE TITLE
Show/Hide Queue with an Icon button in the app bar

### ISSUE THREAD

**Issue by IanWalston** [callbacc/Artistify#8]
the icon button should have a badge that displays the number of songs currently in the queue

**Comment by rguzg** [comment]
Hey, can I work on this issue?

**Comment by callbacc** [comment]
Go ahead ;)

**Comment by rguzg** [comment]
What's the database I should use with the project?

**Comment by IanWalston** [comment]
You shouldn’t need a connection for this feature

**Comment by IanWalston** [comment]
If you want to though, you can change the base url in functions.js to use the production api url in .env so your front end will hit the real backend while you’re developing.

**Comment by IanWalston** [comment]
@rguzg let me know if you're still interested in this issue and i'll assign it to you, otherwise i'm going to pick it up
